### PR TITLE
Quicksort worst case runtime is quadratic, O(n^2)

### PR DESCRIPTION
**Pull request by raypereda**
Doug McIlroy's 1999 paper [“A Killer Adversary for Quicksort”](http://www.cs.dartmouth.edu/~doug/mdmspe.pdf) describes how to find inputs to the sort that exhibit this quadratic behavior.

Here's a discussion on the topic by Russ Cox at http://research.swtch.com/qsort

### CODE REVIEW

**Comment by raypereda** [comment]
@ericdrowell If there is any doubt about the the correctness of the proposal I'm glad to discuss more. Thanks for creating the Big O Cheat Sheet on github!

**Comment by dasilvacontin** [comment]
Please merge! :+1:

**Comment by jaredsburrows** [comment]
I am losing my confidence in this site. This pull request has been open for 10 days with wrong information on something as simple as QuickSort. @ericdrowell  Let's get this merged in please.

**Comment by ericdrowell** [comment]
Thanks guys!  Yea that was just a clerical error.  Thanks for fixing it up.

**Comment by dasilvacontin** [comment]
Nice!

**Comment by 983** [comment]
The paper makes the assumption that "2. Pivot-choosing takes O(1) comparisons" [page 2](http://www.cs.dartmouth.edu/~doug/mdmspe.pdf) However, quicksort could be implemented to use the [median of medians algorithm](https://en.wikipedia.org/wiki/Median_of_medians) for pivot selection which is in `O(n)`, so the resulting quicksort algorithm would be in `O(n log n)`.

**Comment by raypereda** [comment]
@983 In standard quicksort, choosing the pivot is O(1). quicksort with perfect pivot selection, call it quicksort2, is a different algorithm than quicksort. The performance of quicksort2 is different than performance of quicksort. On average, quicksort is going to be faster than quicksort2.

In the [benchmark code](https://gist.github.com/983/7df13d454665373ac2cc#file-median-cpp-L75) you provided, you initialize the array with a[i] = i. That is a special case that is going to do very well with quicksort2. Please try running the benchmark with a[i] = random number between 0 and 5000, or better yet randomly shuffle the array a[i] before running your benchmark. I'd would be interested in seeing the results of the plot after those changes are made.

**Pull request merged**
